/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/diffcp/cones.py:7: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(scs.__version__) >= StrictVersion('3.0.0'):
404 response executing GraphQL.
{"errors":[{"message":"could not find project stowage_planning_research/uncategorized during createAgent","path":["createAgent"]}],"data":{"createAgent":null}}
wandb: ERROR Error while calling W&B API: could not find project stowage_planning_research/uncategorized during createAgent (<Response [404]>)
wandb: ERROR could not find project stowage_planning_research/uncategorized during createAgent
Traceback (most recent call last):
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/jaiv/PycharmProjects/DRL_4_master_planning/sweep.py", line 72, in <module>
    wandb.agent(sweep_id, function=train)
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/wandb_agent.py", line 570, in agent
    return pyagent(sweep_id, function, entity, project, count)
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 356, in pyagent
    agent.run()
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 327, in run
    self._setup()
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 135, in _setup
    self._register()
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 112, in _register
    agent = self._api.register_agent(socket.gethostname(), sweep_id=self._sweep_id)
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/apis/internal.py", line 154, in register_agent
    return self.api.register_agent(*args, **kwargs)
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2959, in register_agent
    response = self.gql(
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/jaiv/.pyenv/versions/master_planning/lib/python3.9/site-packages/wandb/util.py", line 881, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.UsageError: could not find project stowage_planning_research/uncategorized during createAgent
